# Generated by Django 5.2.9 on 2025-12-09 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_kk', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_kk', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('location', models.CharField(max_length=200)),
                ('location_kk', models.CharField(max_length=200, null=True)),
                ('location_ru', models.CharField(max_length=200, null=True)),
                ('location_en', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('fairs', 'Ярмарки / Жәрмеңке / Fairs'), ('seminars', 'Семинары / Семинарлар / Seminars'), ('lectures', 'Guest lectures / Қонақ дәрістері / Guest lectures'), ('psychologist', 'Психолог / Психолог / Psychologist'), ('offsite', 'Выездное / Сырттағы іс-шара / Offsite'), ('parties', 'Вечеринки / Вечеринкалар / Parties'), ('games', 'Игры / Ойындар / Games')], max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('tickets_available', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clubs.club')),
            ],
        ),
    ]
