# Generated by Django 5.2.9 on 2025-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('fairs', 'Ярмарки / Жәрмеңке / Fairs'), ('seminars', 'Семинары / Семинарлар / Seminars'), ('lectures', 'Guest lectures / Қонақ дәрістері / Guest lectures'), ('psychologist', 'Психолог / Психолог / Psychologist'), ('offsite', 'Выездное / Сырттағы іс-шара / Offsite'), ('parties', 'Вечеринки / Вечеринкалар / Parties'), ('games', 'Игры / Ойындар / Games'), ('Hackathons', 'Хакатоны / Хакатондар / Hackathons'), ('Workshops', 'Воркшопы / Воркшоптар / Workshops')], max_length=50),
        ),
    ]
