# Generated by Django 5.2.9 on 2025-12-12 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0001_initial'),
        ('clubs', '0003_alter_club_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmanager',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubmanager_entries', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubmanager_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
