# Generated by Django 5.2.9 on 2025-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='paid',
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('pending', 'Ожидает проверки'), ('paid', 'Оплачен'), ('rejected', 'Отклонён')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
